### ISSUE TITLE
Host Drupal 7 Upgrade Day - Next Wednesday

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdrop-community#14]
What if we declare a prepare for Drupal 7 EOL week sometime in November, leveraging the idea that Drupal 7 EOL is now only one year away.

During that week, we release a series of blogs posts and have several workshops on upgrading/migrating from Drupal 7 to Backdrop.

Maybe we do a press release and try to get something in the weekly drop. Use this week to really try to get some social media traction around Backdrop as a viable alternative to Backdrop.

Maybe even publish a blog post, signed by the PMC with some specific ideas about how to spread the word about Backdrop as an upgrade option for Backdrop CMS. 

Try to get some friendly orgs and individuals to write blogs posts or social media posts on our behalf. A really focused effort.

Maybe Nov 15-21?

**Comment by stpaultim** [comment]
Some specific ideas for this week?

1) Plan a 2-3 hour workshop on planning your Drupal 7 to Backdrop CMS upgrade (maybe during office hours). Tells folks to bring their Drupal 7 sites and we'll walk through the planning stages of preparing for an upgrade to Backdrop. 

2) Plan a upgrade-a-thon. Find a suitable non-profit and upgrade their site for them in 24 hours (working in shifts). Or get as far as we can. The mere act of publicly making this offer to non-profits could get us some social media attention. (I can commit 3 developers for 6 hours each). We can have one person tweeting hourly updates. 

3) Write and issue a press release. 

4) Ask members of the community to write case studies and publish one each day for a week on BackdropCMS.org. All focused on D7 upgrades of different types. 

5) Queue up some provocative social media posts to go out 2-3 times per day all week. 

6) Have a special section open in the forum (maybe we don't need a special section) and make it clear that we'll be watching very closely all week and answering all questions as quickly as possible. 

7) Give away a few T-Shirts...

8) What other ideas do folks have.

**Comment by herbdool** [comment]
I like the idea! I'll see how I can help. I created a blog post about upgrading last year https://www.freeform.ca/upgrading-website-drupal-7-backdrop-cms. Could rehash/revise it and publish on b.org. Would be good to have a FAQ to deal with exceptions/issues too.

**Comment by jenlampton** [comment]
I love it! I'd like to contribute somehow to module conversion, theme conversion, theme into layout conversion, upgrading sites generally, or upgrading block placements in D7 into layouts.

**Comment by stpaultim** [comment]
In the Outreach meeting today we decided to pull something together fairly quickly in conjunction with the EOL of Drupal 8 and expected EOL of Drupal 7 in one year.

Here is the rough outline of what we have in mind.

1) 9-5 (Pacific Time - USA) we have an upgrade your Drupal 7 site day.
2) We use a Zoom room with breakout rooms.
3) In breakout rooms, we schedule a formal presentation at 9:00am on how to upgrade
4) After that, we might do a LIVE upgrade demo (Jen has a site)
5) In the hallway, we have folks available all day to simply answer questions>

We focus on the idea that if you want to start working on your Drupal 7 to Backdrop upgrade on this day, we'll have tools available and a place for you to come and get help or ask questions.

What we need:

1) People to be available for 1-3 hour shifts to just answer questions and provide support.
2) Ideas for how to promote this quickly.
3) Maybe a blog post that we can release next Tuesday about upgrading.

**Comment by stpaultim** [comment]
Here is a Google Doc that I'm using to draft ideas. https://bit.ly/3nHQyCt

**Comment by stpaultim** [comment]
Looking for ideas for social media. What can we post early next week that will get retweeted or shared?

Here is one idea.

![tweets](https://user-images.githubusercontent.com/3144571/139357347-a0a2fbe4-980c-45c4-b9c7-96a31e301aa3.png)

**Comment by stpaultim** [comment]
We had an upgrade day event a few weeks ago. It seemed to go fairly well and at least 1-2 sites were largely upgraded that day, a few new people showed up for our training. 

I'll close this issue, but there was talk of doing this again. If anyone would like to schedule another upgrade day, they can reopen this issue or create a new one.
