### ISSUE TITLE
Revitalize Presence on LinkedIn

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdrop-community#17]
@yorkshire-pudding has started a discussion in Zulip about increasing or revitalizing our presence on LinkedIn and offered to help. I'll post his initial message here:

*"Our general target market is small businesses and small non-profit organisations even if that is not an official policy. While Facebook, Twitter and Instagram have a presence primarily for person to person and business to consumer, LinkedIn is the predominant social network for business to business and for professional services. While we have a LinkedIn group, it does not appear to be actively managed and also does not have the ability to be outward facing. Having a Backdrop CMS company page would allow branded communications to be shared on this platform. The catalyst for setting up a company page is adding a position to employment history with Backdrop CMS as the company (I and others have done this for a charity before so the existence of an employment relationship is not necessary). The person who sets up the page is the super admin who can add other super admins and content admins (there is also an analyst role, but I don't think that would be necessary for us). The other admins do not need to be registered as staff.*

*Probably for the PMC to decide on the approach to this, but I think as a minimum the PMC members should be added (if they use LinkedIn). More could be added (e.g. core committers, other informal roles) which would ultimately raise awareness of the name Backdrop CMS and what it does. It would make sense to agree common role descriptions that can be tailored to particular leads (e.g. modules, functions). I'm happy to help with this having spent a bit of time researching what is needed for my own company page.
Thoughts"*

For the record, here are some past discussions about LinkedIn on Github:

- [Proposal: LinkedIn Group for BackdropCMS](https://github.com/backdrop-ops/backdropcms.org/issues/131)
- [Drop LinkedIn?](https://github.com/backdrop-ops/backdropcms.org/issues/696)

**Comment by stpaultim** [comment]
@yorkshire-pudding - Thanks for bringing this up and for offering to help with it. As I mentioned in Zulip, the main obstacle to us being more active in LinkedIN is having someone to lead the effort. 

For the most part our social media initiatives are driven by interested individuals, not any coordinated effort by the PMC. Whether or not the PMC should be more involved in this is another discussion. For now, I would say that decisions about Social Media are made in any of the following ways:

1) Individuals taking initiative on their own and asking the community for whatever access or help is needed. 
2) Discussions in Github (or Zulip)
3) Discussions at the fortnightly Outreach meetings

In terms of your specific ideas. In terms of the BackdropCMS group on LinkedIN, I think that the appropriate approach would be to simply try to contact the current group admins and ask if you can join the admin group. I would start with @jenlampton, since she is generally available and involved. 

In terms of setting up an official Backdrop CMS "company" page, I think we should simply discuss this at an Outreach meeting and make a decision. I can't see any reason to NOT do it, other than concern that we set it up and then don't manage it. We struggle to maintain our current social media channels. BUT, if you are motivated to give this a go, I would support it and try to help out as I can. 

I've tried to post occasionally to LinkedIN about Backdrop, but my social media energy is mostly consumed by Twitter. I can see where LinkedIN might actually be a better investment of time, I've just not been motivated to participate there. 

I will put this on the agenda for the next Outreach Meeting for discussion. If you are not able to attend, please post any additional thoughts here AND we'll try to respond to any questions and post updates in this issue. If you would like to set up a LinkedIn meeting at a time that works better for you, to strategize, I would be happy to participate.

**Comment by yorkshire-pudding** [comment]
Thanks @stpaultim for pointing me to the older threads.  I don't actually think there's much point in having the group and was really just thinking of the company page.  I am offering to look after it, but I don't want to just add a role to my LinkedIn when I don't yet have a formal role on the project, hence why I thought it could be created and then set me up as a super admin.  Initially I was thinking of posting the same material, but might be a small introduction.  I would also respond to any follow up in the comments.  Over time, it may evolve, but a corporate page isn't reliant on a thriving discussion; even if we can just get our community to follow the page and "like" the announcements that will help to raise our profile.  I actually think it is more important than a group as closed groups don't appear in feeds.

**Comment by yorkshire-pudding** [comment]
@stpaultim I should be able to make the next Outreach meeting on December 9th so very happy to discuss there.

**Comment by stpaultim** [comment]
If we did have a page the organization, I might from time to time post content under that account. Right now, I'm able to post as Backdrop on Twitter and Facebook, but not on LinkedIn. On LinkedIn I have to post as myself. 

I look forward to chatting about this more at the next Outreach meeting.

**Comment by yorkshire-pudding** [comment]
As we now have a company page setup (https://www.linkedin.com/company/backdrop-cms/) and key individuals have been granted admin, I think @stpaultim that we can close this.
