### ISSUE TITLE
Participate in Open Force Event

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdrop-community#21]
We have been invited to participate in the following event for new contributors to Open Source. 

https://www.openforce.tech/ or here is a brochure: https://drive.google.com/file/d/1z1GqyHtHzFY38EZ4JehV8DaqUPNWtN9W/view

They are primarily looking for us to be an OpenSource partner that will make sure we have tickets available and be supportive of any first time contributors. They are offering to provide their own mentors. 

This is an asynchronous event that takes place over several weeks in March. We have the option of hosting some kind of welcome event/session at some point, but the details on that are still unknown and it is optional. 

They have also invited us to be a sponsor, but this is not required (see brochure for details).

![image](https://user-images.githubusercontent.com/3144571/153983646-8d4bd8c9-de2c-442e-b0de-7559ff698b6e.png)

I am unaware of any deadline, however we should make a decision and a commitment pretty soon.

**Comment by klonos** [comment]
Depending on our financials, I think that it would be good marketing/outreach to sponsor this even, even at the lowest tier. I'm not sure if I'll have the capacity to do a welcome event/session (not saying no), but I will as always do my best to be as active as possible in the issue queue, to help people with orientation and/or PRs.

If there is no dedicated channel option for live chat organized by the event organizers, I think that we should ask for permission, and have people interested to contribute to Backdrop go either on our Zulip chat, or dedicated office-hours-style zoom/jitsi sessions.

**Comment by stpaultim** [comment]
I went ahead and met with the folks from OpenForce today. We are officially participating in the event. The only thing that they really require from us is to provide some issues. I'm going to link them to our "Good First Issues" tag, but I think they would also like us to recommend some more advanced issues. 

I'm also going to invite them to Backdrop LIVE and provide them with a link to Zulip. Atten @jenlampton

**Comment by jenlampton** [comment]
I'm also in favor of sponsoring this event, if it's not too late.
