### ISSUE TITLE
Verify Google Search Console is connectected to Google Analytics for Backdropcms.org and forum.backdropcms.org

### ISSUE THREAD

**Issue by rayjamesdev** [backdrop-ops/backdrop-community#26]
Have @jenlampton and @keiserjb verify that Google Search Console is connected.  Jen might need to add Justin as an admin.

**Comment by rayjamesdev** [comment]
Shouldn't be an individual issue.  Sorry about that.

**Comment by jenlampton** [comment]
@rayjamesdev I've added Justin to all 4 backdrop properties, and @stpaultim to the 2 he was not already a member of.
