### ISSUE TITLE
backdrop CMS is good to manage multiple sites from a single dashboard?

### ISSUE THREAD

**Issue by jaydulhsemch** [backdrop-ops/backdrop-community#29]
backdrop CMS is good to manage multiple sites from a single dashboard?

**Comment by izmeez** [comment]
Is this a general question or specific to the backdropcms.org community sites? As a general question it would be good to raise it in the forum https://forum.backdropcms.org I believe there was a drupal module that provided that functionality. I'd have to look it up and I don't know if it's been ported to backdrop.

**Comment by stpaultim** [comment]
Yes, this issue queue is more intended for discussions about building and maintaining the Backdrop CMS community. Better places to get a reply would be the forum or in Zulip.

https://backdrop.zulipchat.com/

Having said that, it's better to post here than nowhere. I've posted this question on forum, in case you are still interested. Feel free to chime in there and add details. https://forum.backdropcms.org/forum/manage-multiple-sites-single-dashboard
