### ISSUE TITLE
Sponsor Twin Cities Drupal Camp

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdrop-community#32]
Twin Cities Drupal Camp is coming up. @wylbur and I are on the planning committee. It is one week before Backdrop LIVE. Bronze sponsorship is only $350. It only comes with:

- Logo placement on the sponsors page of the Twin Cities DrupalCamp website
- Exposure on @tcdrupal twitter feed and other social media accounts
- 1 job posting

The job posting isn't really helpful to us, but the other exposure would be. I expect 100-150 people at this camp, including a lot of people from the University of Minnesota. 

Camp organizers are open to this sponsorship and will be accepting Drupal session proposals (I'm working on 1-2). 

There is also an unconference component to this camp, during which Backdrop can be discussed. 

Thoughts?

**Comment by albanycomputers** [comment]
I'm all for it, but a few questions/observations...  

Has any analysis been done on the "cost of acquisitions"... i.e. the potential for new members/uptake/contributors etc...

Are there any metrics regarding how many clicks the logos get on the website or the job post?

How many followers are there on the Twitter Feed and what's the overall exposure?

Can we make a job posting where it's a non-paid post... just a simple... "Come join Backdrop CMS" bla bla bla...  

If we only get 1 or 2 new members/contributors would the money be better spent on adverts... Google/Bing/X (formerly Twitter)/Instagram etc...

Hope this helps.

**Comment by yorkshire-pudding** [comment]
Does "Logo placement on the sponsors page of the Twin Cities DrupalCamp website" include a link to `b.org`?

If not, are we just trying to increase brand awareness?

How does this sponsorship compare to deals available at bigger Drupal camps?

**Comment by stpaultim** [comment]
Yes, logo placement on the site does include a link - see: https://2023.tcdrupal.org/sponsors

Bronze Sponsorships at other camps:

Forida Drupal Camp - $250 - https://www.fldrupal.camp/become-sponsor
Drupal GovCon - NA - https://www.drupalgovcon.org/how-sponsor
Asheville - $250 - https://www.drupalasheville.com/sponsorship
Atlanta - ???? - https://www.drupalcampatlanta.com/sponsor-levels

@albanycomputers - No, we haven't done the kind of analysis that you suggest. While it would be nice to do this kind of work, it has been discussed often, it's not the kind of thing we usually have resources for. If anyone wants to lead an effort to figure those things out, it would be greatly appreciated.

The argument for sponsorship at a camp like this one is exposure and good will directly at an audience of the most active Drupal users and those actively coming to a camp to look for options and ideas. We will also be submitting sessions at this camp and a sponsorship would reinforce whatever work we do at camp. 

I think it's also a great opportunity to reinforce the growing cooperation we've been experiencing with the Drupal community.

**Comment by yorkshire-pudding** [comment]
I say we should go for it then - there are too many people in Drupal land who still haven't heard of us.

**Comment by keiserjb** [comment]
It's beneficial year-round.  The camp websites don't go away when camp ends.

**Comment by irinaz** [comment]
Completed in 2023
