### ISSUE TITLE
Backdrop LIVE - Create Schedule

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdrop-community#35]
@jenlampton Do we have an automated way to generate all the time slots for the next Backdrop LIVE or should we go ahead and do this manually?

**Comment by jenlampton** [comment]
@stpaultim it's automated. But I expect you have found the button by now :) 

For future reference  -- or for anyone who is reading this comment in the future and has no idea what "button" I am talking about -- there is a page specifically for Backdrop LIVE administration, that includes documentation, and automated processes for the things we do for each event. One of those things is updating time slots. 

The time slot feature asks for the day and of the first time slot (pulling the default date from the currently selected event) and then automatically updates all existing time slot terms based on that start time. **It does assume 3 hours each block, and 3 hour breaks between, so if the first block will only be 2 hours, then you need to subtract an hour when setting the start time.**

**Comment by stpaultim** [comment]
@jenlampton Thanks. I'll close this issue again, since we figured out the problems. 

I did require the devel module to use this button and the devel module was not available on the live site. However, thanks for fixing that. 

Since that was added, I was able to easily generate two sessions for each time slot, which is a good starting point.
